
// ToolsLib Project

/* ToolsLib library for RusRoute firewall and other projects of
 * Andrey A. Moiseenko / IE Moiseenko A.A. (Russia)
 * e-mail: support@maasoftware.ru, maa2002@mail.ru
 * web: http://maasoftware.ru, http://maasoftware.com, http://maasoft.ru, http://maasoft.org
 * Author's full name: Andrey Alekseevitch Moiseenko
 * (russian name: Моисеенко Андрей Алексеевич)
 */

// ToolsLib/winerrors.h

/* Copyright (C) 2002-2024 Andrey A. Moiseenko (support@maasoftware.ru)
 * All rights reserved.
 *
 * This folder contains Windows specific and obsolete code.
 * The library implementation written
 * by Andrey A. Moiseenko (support@maasoftware.ru).
 * This library and applications are
 * FREE FOR COMMERCIAL AND NON-COMMERCIAL USE
 * as long as the following conditions are aheared to.
 *
 * Copyright remains Andrey A. Moiseenko, and as such any Copyright notices in
 * the code are not to be removed.  If this code is used in a product,
 * Andrey A. Moiseenko should be given attribution as the author of the parts used.
 * This can be in the form of a textual message at program startup or
 * in documentation (online or textual) provided with the package.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *    This product includes software developed by Andrey A. Moiseenko (support@maasoftware.ru)
 *
 * THIS SOFTWARE IS PROVIDED BY ANDREY A. MOISEENKO ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * The licence and distribution terms for any publically available version or
 * derivative of this code cannot be changed.  i.e. this code cannot simply be
 * copied and put under another distribution licence
 * [including the GNU Public Licence.]
 */


#ifdef WSAEINTR
ADD_WSA_ERR(WSAEINTR, "WSAEINTR"),
#endif
#ifdef WSAEBADF
ADD_WSA_ERR(WSAEBADF, "WSAEBADF"),
#endif
#ifdef WSAEACCES
ADD_WSA_ERR(WSAEACCES, "WSAEACCES"),
#endif
#ifdef WSAEFAULT
ADD_WSA_ERR(WSAEFAULT, "WSAEFAULT"),
#endif
#ifdef WSAEINVAL
ADD_WSA_ERR(WSAEINVAL, "WSAEINVAL"),
#endif
#ifdef WSAEMFILE
ADD_WSA_ERR(WSAEMFILE, "WSAEMFILE"),
#endif
#ifdef WSAEWOULDBLOCK
ADD_WSA_ERR(WSAEWOULDBLOCK, "WSAEWOULDBLOCK"),
#endif
#ifdef WSAEINPROGRESS
ADD_WSA_ERR(WSAEINPROGRESS, "WSAEINPROGRESS"),
#endif
#ifdef WSAEALREADY
ADD_WSA_ERR(WSAEALREADY, "WSAEALREADY"),
#endif
#ifdef WSAENOTSOCK
ADD_WSA_ERR(WSAENOTSOCK, "WSAENOTSOCK"),
#endif
#ifdef WSAEDESTADDRREQ
ADD_WSA_ERR(WSAEDESTADDRREQ, "WSAEDESTADDRREQ"),
#endif
#ifdef WSAEMSGSIZE
ADD_WSA_ERR(WSAEMSGSIZE, "WSAEMSGSIZE"),
#endif
#ifdef WSAEPROTOTYPE
ADD_WSA_ERR(WSAEPROTOTYPE, "WSAEPROTOTYPE"),
#endif
#ifdef WSAENOPROTOOPT
ADD_WSA_ERR(WSAENOPROTOOPT, "WSAENOPROTOOPT"),
#endif
#ifdef WSAEPROTONOSUPPORT
ADD_WSA_ERR(WSAEPROTONOSUPPORT, "WSAEPROTONOSUPPORT"),
#endif
#ifdef WSAESOCKTNOSUPPORT
ADD_WSA_ERR(WSAESOCKTNOSUPPORT, "WSAESOCKTNOSUPPORT"),
#endif
#ifdef WSAEOPNOTSUPP
ADD_WSA_ERR(WSAEOPNOTSUPP, "WSAEOPNOTSUPP"),
#endif
#ifdef WSAEPFNOSUPPORT
ADD_WSA_ERR(WSAEPFNOSUPPORT, "WSAEPFNOSUPPORT"),
#endif
#ifdef WSAEAFNOSUPPORT
ADD_WSA_ERR(WSAEAFNOSUPPORT, "WSAEAFNOSUPPORT"),
#endif
#ifdef WSAEADDRINUSE
ADD_WSA_ERR(WSAEADDRINUSE, "WSAEADDRINUSE"),
#endif
#ifdef WSAEADDRNOTAVAIL
ADD_WSA_ERR(WSAEADDRNOTAVAIL, "WSAEADDRNOTAVAIL"),
#endif
#ifdef WSAENETDOWN
ADD_WSA_ERR(WSAENETDOWN, "WSAENETDOWN"),
#endif
#ifdef WSAENETUNREACH
ADD_WSA_ERR(WSAENETUNREACH, "WSAENETUNREACH"),
#endif
#ifdef WSAENETRESET
ADD_WSA_ERR(WSAENETRESET, "WSAENETRESET"),
#endif
#ifdef WSAECONNABORTED
ADD_WSA_ERR(WSAECONNABORTED, "WSAECONNABORTED"),
#endif
#ifdef WSAECONNRESET
ADD_WSA_ERR(WSAECONNRESET, "WSAECONNRESET"),
#endif
#ifdef WSAENOBUFS
ADD_WSA_ERR(WSAENOBUFS, "WSAENOBUFS"),
#endif
#ifdef WSAEISCONN
ADD_WSA_ERR(WSAEISCONN, "WSAEISCONN"),
#endif
#ifdef WSAENOTCONN
ADD_WSA_ERR(WSAENOTCONN, "WSAENOTCONN"),
#endif
#ifdef WSAESHUTDOWN
ADD_WSA_ERR(WSAESHUTDOWN, "WSAESHUTDOWN"),
#endif
#ifdef WSAETOOMANYREFS
ADD_WSA_ERR(WSAETOOMANYREFS, "WSAETOOMANYREFS"),
#endif
#ifdef WSAETIMEDOUT
ADD_WSA_ERR(WSAETIMEDOUT, "WSAETIMEDOUT"),
#endif
#ifdef WSAECONNREFUSED
ADD_WSA_ERR(WSAECONNREFUSED, "WSAECONNREFUSED"),
#endif
#ifdef WSAELOOP
ADD_WSA_ERR(WSAELOOP, "WSAELOOP"),
#endif
#ifdef WSAENAMETOOLONG
ADD_WSA_ERR(WSAENAMETOOLONG, "WSAENAMETOOLONG"),
#endif
#ifdef WSAEHOSTDOWN
ADD_WSA_ERR(WSAEHOSTDOWN, "WSAEHOSTDOWN"),
#endif
#ifdef WSAEHOSTUNREACH
ADD_WSA_ERR(WSAEHOSTUNREACH, "WSAEHOSTUNREACH"),
#endif
#ifdef WSAENOTEMPTY
ADD_WSA_ERR(WSAENOTEMPTY, "WSAENOTEMPTY"),
#endif
#ifdef WSAEPROCLIM
ADD_WSA_ERR(WSAEPROCLIM, "WSAEPROCLIM"),
#endif
#ifdef WSAEUSERS
ADD_WSA_ERR(WSAEUSERS, "WSAEUSERS"),
#endif
#ifdef WSAEDQUOT
ADD_WSA_ERR(WSAEDQUOT, "WSAEDQUOT"),
#endif
#ifdef WSAESTALE
ADD_WSA_ERR(WSAESTALE, "WSAESTALE"),
#endif
#ifdef WSAEREMOTE
ADD_WSA_ERR(WSAEREMOTE, "WSAEREMOTE"),
#endif
#ifdef WSASYSNOTREADY
ADD_WSA_ERR(WSASYSNOTREADY, "WSASYSNOTREADY"),
#endif
#ifdef WSAVERNOTSUPPORTED
ADD_WSA_ERR(WSAVERNOTSUPPORTED, "WSAVERNOTSUPPORTED"),
#endif
#ifdef WSANOTINITIALISED
ADD_WSA_ERR(WSANOTINITIALISED, "WSANOTINITIALISED"),
#endif
#ifdef WSAEDISCON
ADD_WSA_ERR(WSAEDISCON, "WSAEDISCON"),
#endif
#ifdef WSAENOMORE
ADD_WSA_ERR(WSAENOMORE, "WSAENOMORE"),
#endif
#ifdef WSAECANCELLED
ADD_WSA_ERR(WSAECANCELLED, "WSAECANCELLED"),
#endif
#ifdef WSAEINVALIDPROCTABLE
ADD_WSA_ERR(WSAEINVALIDPROCTABLE, "WSAEINVALIDPROCTABLE"),
#endif
#ifdef WSAEINVALIDPROVIDER
ADD_WSA_ERR(WSAEINVALIDPROVIDER, "WSAEINVALIDPROVIDER"),
#endif
#ifdef WSAEPROVIDERFAILEDINIT
ADD_WSA_ERR(WSAEPROVIDERFAILEDINIT, "WSAEPROVIDERFAILEDINIT"),
#endif
#ifdef WSASYSCALLFAILURE
ADD_WSA_ERR(WSASYSCALLFAILURE, "WSASYSCALLFAILURE"),
#endif
#ifdef WSASERVICE_NOT_FOUND
ADD_WSA_ERR(WSASERVICE_NOT_FOUND, "WSASERVICE_NOT_FOUND"),
#endif
#ifdef WSATYPE_NOT_FOUND
ADD_WSA_ERR(WSATYPE_NOT_FOUND, "WSATYPE_NOT_FOUND"),
#endif
#ifdef WSA_E_NO_MORE
ADD_WSA_ERR(WSA_E_NO_MORE, "WSA_E_NO_MORE"),
#endif
#ifdef WSA_E_CANCELLED
ADD_WSA_ERR(WSA_E_CANCELLED, "WSA_E_CANCELLED"),
#endif
#ifdef WSAEREFUSED
ADD_WSA_ERR(WSAEREFUSED, "WSAEREFUSED"),
#endif
#ifdef WSAHOST_NOT_FOUND
ADD_WSA_ERR(WSAHOST_NOT_FOUND, "WSAHOST_NOT_FOUND"),
#endif
#ifdef WSATRY_AGAIN
ADD_WSA_ERR(WSATRY_AGAIN, "WSATRY_AGAIN"),
#endif
#ifdef WSANO_RECOVERY
ADD_WSA_ERR(WSANO_RECOVERY, "WSANO_RECOVERY"),
#endif
#ifdef WSANO_DATA
ADD_WSA_ERR(WSANO_DATA, "WSANO_DATA"),
#endif
#ifdef WSA_QOS_RECEIVERS
ADD_WSA_ERR(WSA_QOS_RECEIVERS, "WSA_QOS_RECEIVERS"),
#endif
#ifdef WSA_QOS_SENDERS
ADD_WSA_ERR(WSA_QOS_SENDERS, "WSA_QOS_SENDERS"),
#endif
#ifdef WSA_QOS_NO_SENDERS
ADD_WSA_ERR(WSA_QOS_NO_SENDERS, "WSA_QOS_NO_SENDERS"),
#endif
#ifdef WSA_QOS_NO_RECEIVERS
ADD_WSA_ERR(WSA_QOS_NO_RECEIVERS, "WSA_QOS_NO_RECEIVERS"),
#endif
#ifdef WSA_QOS_REQUEST_CONFIRMED
ADD_WSA_ERR(WSA_QOS_REQUEST_CONFIRMED, "WSA_QOS_REQUEST_CONFIRMED"),
#endif
#ifdef WSA_QOS_ADMISSION_FAILURE
ADD_WSA_ERR(WSA_QOS_ADMISSION_FAILURE, "WSA_QOS_ADMISSION_FAILURE"),
#endif
#ifdef WSA_QOS_POLICY_FAILURE
ADD_WSA_ERR(WSA_QOS_POLICY_FAILURE, "WSA_QOS_POLICY_FAILURE"),
#endif
#ifdef WSA_QOS_BAD_STYLE
ADD_WSA_ERR(WSA_QOS_BAD_STYLE, "WSA_QOS_BAD_STYLE"),
#endif
#ifdef WSA_QOS_BAD_OBJECT
ADD_WSA_ERR(WSA_QOS_BAD_OBJECT, "WSA_QOS_BAD_OBJECT"),
#endif
#ifdef WSA_QOS_TRAFFIC_CTRL_ERROR
ADD_WSA_ERR(WSA_QOS_TRAFFIC_CTRL_ERROR, "WSA_QOS_TRAFFIC_CTRL_ERROR"),
#endif
#ifdef WSA_QOS_GENERIC_ERROR
ADD_WSA_ERR(WSA_QOS_GENERIC_ERROR, "WSA_QOS_GENERIC_ERROR"),
#endif
#ifdef WSA_QOS_ESERVICETYPE
ADD_WSA_ERR(WSA_QOS_ESERVICETYPE, "WSA_QOS_ESERVICETYPE"),
#endif
#ifdef WSA_QOS_EFLOWSPEC
ADD_WSA_ERR(WSA_QOS_EFLOWSPEC, "WSA_QOS_EFLOWSPEC"),
#endif
#ifdef WSA_QOS_EPROVSPECBUF
ADD_WSA_ERR(WSA_QOS_EPROVSPECBUF, "WSA_QOS_EPROVSPECBUF"),
#endif
#ifdef WSA_QOS_EFILTERSTYLE
ADD_WSA_ERR(WSA_QOS_EFILTERSTYLE, "WSA_QOS_EFILTERSTYLE"),
#endif
#ifdef WSA_QOS_EFILTERTYPE
ADD_WSA_ERR(WSA_QOS_EFILTERTYPE, "WSA_QOS_EFILTERTYPE"),
#endif
#ifdef WSA_QOS_EFILTERCOUNT
ADD_WSA_ERR(WSA_QOS_EFILTERCOUNT, "WSA_QOS_EFILTERCOUNT"),
#endif
#ifdef WSA_QOS_EOBJLENGTH
ADD_WSA_ERR(WSA_QOS_EOBJLENGTH, "WSA_QOS_EOBJLENGTH"),
#endif
#ifdef WSA_QOS_EFLOWCOUNT
ADD_WSA_ERR(WSA_QOS_EFLOWCOUNT, "WSA_QOS_EFLOWCOUNT"),
#endif
#ifdef WSA_QOS_EUNKOWNPSOBJ
ADD_WSA_ERR(WSA_QOS_EUNKOWNPSOBJ, "WSA_QOS_EUNKOWNPSOBJ"),
#endif
#ifdef WSA_QOS_EPOLICYOBJ
ADD_WSA_ERR(WSA_QOS_EPOLICYOBJ, "WSA_QOS_EPOLICYOBJ"),
#endif
#ifdef WSA_QOS_EFLOWDESC
ADD_WSA_ERR(WSA_QOS_EFLOWDESC, "WSA_QOS_EFLOWDESC"),
#endif
#ifdef WSA_QOS_EPSFLOWSPEC
ADD_WSA_ERR(WSA_QOS_EPSFLOWSPEC, "WSA_QOS_EPSFLOWSPEC"),
#endif
#ifdef WSA_QOS_EPSFILTERSPEC
ADD_WSA_ERR(WSA_QOS_EPSFILTERSPEC, "WSA_QOS_EPSFILTERSPEC"),
#endif
#ifdef WSA_QOS_ESDMODEOBJ
ADD_WSA_ERR(WSA_QOS_ESDMODEOBJ, "WSA_QOS_ESDMODEOBJ"),
#endif
#ifdef WSA_QOS_ESHAPERATEOBJ
ADD_WSA_ERR(WSA_QOS_ESHAPERATEOBJ, "WSA_QOS_ESHAPERATEOBJ"),
#endif
#ifdef WSA_QOS_RESERVED_PETYPE
ADD_WSA_ERR(WSA_QOS_RESERVED_PETYPE, "WSA_QOS_RESERVED_PETYPE"),
#endif

#ifdef HOST_NOT_FOUND
ADD_WSA_ERR(HOST_NOT_FOUND, "WSAHOST_NOT_FOUND"),
#endif
#ifdef TRY_AGAIN
ADD_WSA_ERR(TRY_AGAIN, "WSATRY_AGAIN"),
#endif
#ifdef NO_RECOVERY
ADD_WSA_ERR(NO_RECOVERY, "WSANO_RECOVERY"),
#endif
#ifdef NO_DATA
ADD_WSA_ERR(NO_DATA, "WSANO_DATA"),
#endif
#ifdef WSANO_ADDRESS
ADD_WSA_ERR(WSANO_ADDRESS, "WSANO_DATA"),
#endif
#ifdef NO_ADDRESS
ADD_WSA_ERR(NO_ADDRESS, "WSANO_ADDRESS"),
#endif
