#ifdef EPERM
ADD_WSA_ERR(EPERM, "EPERM"),
#endif
#ifdef ENOENT
ADD_WSA_ERR(ENOENT, "ENOENT"),
#endif
#ifdef ESRCH
ADD_WSA_ERR(ESRCH, "ESRCH"),
#endif
#ifdef EINTR
ADD_WSA_ERR(EINTR, "EINTR"),
#endif
#ifdef EIO
ADD_WSA_ERR(EIO, "EIO"),
#endif
#ifdef ENXIO
ADD_WSA_ERR(ENXIO, "ENXIO"),
#endif
#ifdef E2BIG
ADD_WSA_ERR(E2BIG, "E2BIG"),
#endif
#ifdef ENOEXEC
ADD_WSA_ERR(ENOEXEC, "ENOEXEC"),
#endif
#ifdef EBADF
ADD_WSA_ERR(EBADF, "EBADF"),
#endif
#ifdef ECHILD
ADD_WSA_ERR(ECHILD, "ECHILD"),
#endif
#ifdef EAGAIN
ADD_WSA_ERR(EAGAIN, "EAGAIN"),
#endif
#ifdef ENOMEM
ADD_WSA_ERR(ENOMEM, "ENOMEM"),
#endif
#ifdef EACCES
ADD_WSA_ERR(EACCES, "EACCES"),
#endif
#ifdef EFAULT
ADD_WSA_ERR(EFAULT, "EFAULT"),
#endif
#ifdef ENOTBLK
ADD_WSA_ERR(ENOTBLK, "ENOTBLK"),
#endif
#ifdef EBUSY
ADD_WSA_ERR(EBUSY, "EBUSY"),
#endif
#ifdef EEXIST
ADD_WSA_ERR(EEXIST, "EEXIST"),
#endif
#ifdef EXDEV
ADD_WSA_ERR(EXDEV, "EXDEV"),
#endif
#ifdef ENODEV
ADD_WSA_ERR(ENODEV, "ENODEV"),
#endif
#ifdef ENOTDIR
ADD_WSA_ERR(ENOTDIR, "ENOTDIR"),
#endif
#ifdef EISDIR
ADD_WSA_ERR(EISDIR, "EISDIR"),
#endif
#ifdef EINVAL
ADD_WSA_ERR(EINVAL, "EINVAL"),
#endif
#ifdef ENFILE
ADD_WSA_ERR(ENFILE, "ENFILE"),
#endif
#ifdef EMFILE
ADD_WSA_ERR(EMFILE, "EMFILE"),
#endif
#ifdef ENOTTY
ADD_WSA_ERR(ENOTTY, "ENOTTY"),
#endif
#ifdef ETXTBSY
ADD_WSA_ERR(ETXTBSY, "ETXTBSY"),
#endif
#ifdef EFBIG
ADD_WSA_ERR(EFBIG, "EFBIG"),
#endif
#ifdef ENOSPC
ADD_WSA_ERR(ENOSPC, "ENOSPC"),
#endif
#ifdef ESPIPE
ADD_WSA_ERR(ESPIPE, "ESPIPE"),
#endif
#ifdef EROFS
ADD_WSA_ERR(EROFS, "EROFS"),
#endif
#ifdef EMLINK
ADD_WSA_ERR(EMLINK, "EMLINK"),
#endif
#ifdef EPIPE
ADD_WSA_ERR(EPIPE, "EPIPE"),
#endif
#ifdef EDOM
ADD_WSA_ERR(EDOM, "EDOM"),
#endif
#ifdef ERANGE
ADD_WSA_ERR(ERANGE, "ERANGE"),
#endif


#ifdef EDEADLK
ADD_WSA_ERR(EDEADLK, "EDEADLK"),
#endif
#ifdef ENAMETOOLONG
ADD_WSA_ERR(ENAMETOOLONG, "ENAMETOOLONG"),
#endif
#ifdef ENOLCK
ADD_WSA_ERR(ENOLCK, "ENOLCK"),
#endif
#ifdef ENOSYS
ADD_WSA_ERR(ENOSYS, "ENOSYS"),
#endif
#ifdef ENOTEMPTY
ADD_WSA_ERR(ENOTEMPTY, "ENOTEMPTY"),
#endif
#ifdef ELOOP
ADD_WSA_ERR(ELOOP, "ELOOP"),
#endif
#ifdef EWOULDBLOCK
ADD_WSA_ERR(EWOULDBLOCK, "EAGAIN"),
#endif
#ifdef ENOMSG
ADD_WSA_ERR(ENOMSG, "ENOMSG"),
#endif
#ifdef EIDRM
ADD_WSA_ERR(EIDRM, "EIDRM"),
#endif
#ifdef ECHRNG
ADD_WSA_ERR(ECHRNG, "ECHRNG"),
#endif
#ifdef EL2NSYNC
ADD_WSA_ERR(EL2NSYNC, "EL2NSYNC"),
#endif
#ifdef EL3HLT
ADD_WSA_ERR(EL3HLT, "EL3HLT"),
#endif
#ifdef EL3RST
ADD_WSA_ERR(EL3RST, "EL3RST"),
#endif
#ifdef ELNRNG
ADD_WSA_ERR(ELNRNG, "ELNRNG"),
#endif
#ifdef EUNATCH
ADD_WSA_ERR(EUNATCH, "EUNATCH"),
#endif
#ifdef ENOCSI
ADD_WSA_ERR(ENOCSI, "ENOCSI"),
#endif
#ifdef EL2HLT
ADD_WSA_ERR(EL2HLT, "EL2HLT"),
#endif
#ifdef EBADE
ADD_WSA_ERR(EBADE, "EBADE"),
#endif
#ifdef EBADR
ADD_WSA_ERR(EBADR, "EBADR"),
#endif
#ifdef EXFULL
ADD_WSA_ERR(EXFULL, "EXFULL"),
#endif
#ifdef ENOANO
ADD_WSA_ERR(ENOANO, "ENOANO"),
#endif
#ifdef EBADRQC
ADD_WSA_ERR(EBADRQC, "EBADRQC"),
#endif
#ifdef EBADSLT
ADD_WSA_ERR(EBADSLT, "EBADSLT"),
#endif
#ifdef EBFONT
ADD_WSA_ERR(EBFONT, "EBFONT"),
#endif
#ifdef ENOSTR
ADD_WSA_ERR(ENOSTR, "ENOSTR"),
#endif
#ifdef ENODATA
ADD_WSA_ERR(ENODATA, "ENODATA"),
#endif
#ifdef ETIME
ADD_WSA_ERR(ETIME, "ETIME"),
#endif
#ifdef ENOSR
ADD_WSA_ERR(ENOSR, "ENOSR"),
#endif
#ifdef ENONET
ADD_WSA_ERR(ENONET, "ENONET"),
#endif
#ifdef ENOPKG
ADD_WSA_ERR(ENOPKG, "ENOPKG"),
#endif
#ifdef EREMOTE
ADD_WSA_ERR(EREMOTE, "EREMOTE"),
#endif
#ifdef ENOLINK
ADD_WSA_ERR(ENOLINK, "ENOLINK"),
#endif
#ifdef EADV
ADD_WSA_ERR(EADV, "EADV"),
#endif
#ifdef ESRMNT
ADD_WSA_ERR(ESRMNT, "ESRMNT"),
#endif
#ifdef ECOMM
ADD_WSA_ERR(ECOMM, "ECOMM"),
#endif
#ifdef EPROTO
ADD_WSA_ERR(EPROTO, "EPROTO"),
#endif
#ifdef EMULTIHOP
ADD_WSA_ERR(EMULTIHOP, "EMULTIHOP"),
#endif
#ifdef EDOTDOT
ADD_WSA_ERR(EDOTDOT, "EDOTDOT"),
#endif
#ifdef EBADMSG
ADD_WSA_ERR(EBADMSG, "EBADMSG"),
#endif
#ifdef EOVERFLOW
ADD_WSA_ERR(EOVERFLOW, "EOVERFLOW"),
#endif
#ifdef ENOTUNIQ
ADD_WSA_ERR(ENOTUNIQ, "ENOTUNIQ"),
#endif
#ifdef EBADFD
ADD_WSA_ERR(EBADFD, "EBADFD"),
#endif
#ifdef EREMCHG
ADD_WSA_ERR(EREMCHG, "EREMCHG"),
#endif
#ifdef ELIBACC
ADD_WSA_ERR(ELIBACC, "ELIBACC"),
#endif
#ifdef ELIBBAD
ADD_WSA_ERR(ELIBBAD, "ELIBBAD"),
#endif
#ifdef ELIBSCN
ADD_WSA_ERR(ELIBSCN, "ELIBSCN"),
#endif
#ifdef ELIBMAX
ADD_WSA_ERR(ELIBMAX, "ELIBMAX"),
#endif
#ifdef ELIBEXEC
ADD_WSA_ERR(ELIBEXEC, "ELIBEXEC"),
#endif
#ifdef EILSEQ
ADD_WSA_ERR(EILSEQ, "EILSEQ"),
#endif
#ifdef ERESTART
ADD_WSA_ERR(ERESTART, "ERESTART"),
#endif
#ifdef ESTRPIPE
ADD_WSA_ERR(ESTRPIPE, "ESTRPIPE"),
#endif
#ifdef EUSERS
ADD_WSA_ERR(EUSERS, "EUSERS"),
#endif
#ifdef ENOTSOCK
ADD_WSA_ERR(ENOTSOCK, "ENOTSOCK"),
#endif
#ifdef EDESTADDRREQ
ADD_WSA_ERR(EDESTADDRREQ, "EDESTADDRREQ"),
#endif
#ifdef EMSGSIZE
ADD_WSA_ERR(EMSGSIZE, "EMSGSIZE"),
#endif
#ifdef EPROTOTYPE
ADD_WSA_ERR(EPROTOTYPE, "EPROTOTYPE"),
#endif
#ifdef ENOPROTOOPT
ADD_WSA_ERR(ENOPROTOOPT, "ENOPROTOOPT"),
#endif
#ifdef EPROTONOSUPPORT
ADD_WSA_ERR(EPROTONOSUPPORT, "EPROTONOSUPPORT"),
#endif
#ifdef ESOCKTNOSUPPORT
ADD_WSA_ERR(ESOCKTNOSUPPORT, "ESOCKTNOSUPPORT"),
#endif
#ifdef EOPNOTSUPP
ADD_WSA_ERR(EOPNOTSUPP, "EOPNOTSUPP"),
#endif
#ifdef EPFNOSUPPORT
ADD_WSA_ERR(EPFNOSUPPORT, "EPFNOSUPPORT"),
#endif
#ifdef EAFNOSUPPORT
ADD_WSA_ERR(EAFNOSUPPORT, "EAFNOSUPPORT"),
#endif
#ifdef EADDRINUSE
ADD_WSA_ERR(EADDRINUSE, "EADDRINUSE"),
#endif
#ifdef EADDRNOTAVAIL
ADD_WSA_ERR(EADDRNOTAVAIL, "EADDRNOTAVAIL"),
#endif
#ifdef ENETDOWN
ADD_WSA_ERR(ENETDOWN, "ENETDOWN"),
#endif
#ifdef ENETUNREACH
ADD_WSA_ERR(ENETUNREACH, "ENETUNREACH"),
#endif
#ifdef ENETRESET
ADD_WSA_ERR(ENETRESET, "ENETRESET"),
#endif
#ifdef ECONNABORTED
ADD_WSA_ERR(ECONNABORTED, "ECONNABORTED"),
#endif
#ifdef ECONNRESET
ADD_WSA_ERR(ECONNRESET, "ECONNRESET"),
#endif
#ifdef ENOBUFS
ADD_WSA_ERR(ENOBUFS, "ENOBUFS"),
#endif
#ifdef EISCONN
ADD_WSA_ERR(EISCONN, "EISCONN"),
#endif
#ifdef ENOTCONN
ADD_WSA_ERR(ENOTCONN, "ENOTCONN"),
#endif
#ifdef ESHUTDOWN
ADD_WSA_ERR(ESHUTDOWN, "ESHUTDOWN"),
#endif
#ifdef ETOOMANYREFS
ADD_WSA_ERR(ETOOMANYREFS, "ETOOMANYREFS"),
#endif
#ifdef ETIMEDOUT
ADD_WSA_ERR(ETIMEDOUT, "ETIMEDOUT"),
#endif
#ifdef ECONNREFUSED
ADD_WSA_ERR(ECONNREFUSED, "ECONNREFUSED"),
#endif
#ifdef EHOSTDOWN
ADD_WSA_ERR(EHOSTDOWN, "EHOSTDOWN"),
#endif
#ifdef EHOSTUNREACH
ADD_WSA_ERR(EHOSTUNREACH, "EHOSTUNREACH"),
#endif
#ifdef EALREADY
ADD_WSA_ERR(EALREADY, "EALREADY"),
#endif
#ifdef EINPROGRESS
ADD_WSA_ERR(EINPROGRESS, "EINPROGRESS"),
#endif
#ifdef ESTALE
ADD_WSA_ERR(ESTALE, "ESTALE"),
#endif
#ifdef EUCLEAN
ADD_WSA_ERR(EUCLEAN, "EUCLEAN"),
#endif
#ifdef ENOTNAM
ADD_WSA_ERR(ENOTNAM, "ENOTNAM"),
#endif
#ifdef ENAVAIL
ADD_WSA_ERR(ENAVAIL, "ENAVAIL"),
#endif
#ifdef EISNAM
ADD_WSA_ERR(EISNAM, "EISNAM"),
#endif
#ifdef EREMOTEIO
ADD_WSA_ERR(EREMOTEIO, "EREMOTEIO"),
#endif
#ifdef EDQUOT
ADD_WSA_ERR(EDQUOT, "EDQUOT"),
#endif
#ifdef ENOMEDIUM
ADD_WSA_ERR(ENOMEDIUM, "ENOMEDIUM"),
#endif
#ifdef EMEDIUMTYPE
ADD_WSA_ERR(EMEDIUMTYPE, "EMEDIUMTYPE"),
#endif
#ifdef ECANCELED
ADD_WSA_ERR(ECANCELED, "ECANCELED"),
#endif
#ifdef ENOKEY
ADD_WSA_ERR(ENOKEY, "ENOKEY"),
#endif
#ifdef EKEYEXPIRED
ADD_WSA_ERR(EKEYEXPIRED, "EKEYEXPIRED"),
#endif
#ifdef EKEYREVOKED
ADD_WSA_ERR(EKEYREVOKED, "EKEYREVOKED"),
#endif
#ifdef EKEYREJECTED
ADD_WSA_ERR(EKEYREJECTED, "EKEYREJECTED"),
#endif
#ifdef EOWNERDEAD
ADD_WSA_ERR(EOWNERDEAD, "EOWNERDEAD"),
#endif
#ifdef ENOTRECOVERABLE
ADD_WSA_ERR(ENOTRECOVERABLE, "ENOTRECOVERABLE"),
#endif
